<?php

namespace StockBundle\Repository;

/**
 * FabriquantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FabriquantRepository extends \Doctrine\ORM\EntityRepository
{
}
