<?php

namespace StockBundle\Repository;

/**
 * ProduitCmdRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProduitCmdRepository extends \Doctrine\ORM\EntityRepository
{
}
