<?php

namespace AppBundle\Repository;

/**
 * UserSecRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserSecRepository extends \Doctrine\ORM\EntityRepository
{
}
