<?php

namespace VenteBundle\Repository;

/**
 * MaladeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MaladeRepository extends \Doctrine\ORM\EntityRepository
{
}
