<?php

namespace VenteBundle\Repository;

/**
 * produitVenduRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class produitVenduRepository extends \Doctrine\ORM\EntityRepository
{
}
